config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users/homes#top'
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  namespace :admin do
    
    resources :posts, only: [:index, :edit, :update, :destroy]
    
    resources :plans, only: [:index, :edit, :update, :destroy]
    
    resources :users, only: [:index, :show]
    
    get '/unsubscribe' => 'admin#unsubscribe', as: 'confirm_unsubscribe'
    get '/withdraw' => 'admin#withdraw'
    patch '/withdraw' => 'admin#withdraw' 
    
  end

  namespace :users do
    
    get '/about' => 'homes#about'
    get '/my_page' => 'users#show'
    patch '/my_page' => 'users#update'
    delete '/users/sign_out' => 'sessions#destroy'
    
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    
    resources :plans, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    
    resources :users, only: [:show, :edit, :update]
    
    get '/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    get '/withdraw' => 'users#withdraw'
    patch '/withdraw' => 'users#withdraw' 
    
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < ApplicationController
    
  def index
    @plans = Plan.all
    @names = Plan.page(params[:page])
  end

  def new
    @plan = Plan.new
  end
  
  def create
    @plan = Plan.new(plan_params)
    @plan.save
    redirect_to users_plans_path
  end
  
  def show
    @plan = Plan.find(params[:id])
    @plans = Plan.all
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    @plan.update(plan_params)
    redirect_to users_plans_path
  end
  
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy(plan_params)
    redirect_to users_plans_path
  end
  
  private
  
  def plan_params
    params.require(:plan).permit(:time, :schedule, :meal, :city_name, :lodgment_target_name)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def unsubscribe
    @user = current_user # current_user.id?
  end
  
  def withdraw
    @user = current_user # current_user.id?
    @user.update(is_active: false)
    reset_session
    redirect_to admin_users_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :encrypted_password, :uid, :provider, :is_active)
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController

  def top
  end
  
  def about
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/plans_controller.rb
class Users::PlansController < ApplicationController
    
  def index
    @plans = Plan.all
    @names = Plan.page(params[:page])
  end

  def new
    @plan = Plan.new
  end
  
  def create
    @plan = Plan.new(plan_params)
    @plan.save
    redirect_to users_plans_path
  end
  
  def show
    @plan = Plan.find(params[:id])
    @plans = Plan.all
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    @plan.update(plan_params)
    redirect_to users_plans_path
  end
  
  private
  
  def plan_params
    params.require(:plan).permit(:time, :schedule, :meal, :city_name, :lodgment_target_name)
  end
  
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
    
  def index
    @posts = Post.all
    @names = Post.page(params[:page])
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to users_posts_path
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to users_posts_path
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy(post_params)
    redirect_to users_posts_path
  end
  
  private
  
  def post_params
    params.permit(:facility_name, :address, :genre, :review, :url, :breakfast_existence)
  end
  
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::PlansController < ApplicationController
    
  def show
    @user = current_user
  end
    
  def edit
    @user = current_user
  end
    
  def update
    @user = current_user
    @user.update(user_params)
    redirect_to users_my_page_path
  end
  
  def unsubscribe
    @user = current_user
  end
  
  def withdraw
    @user = current_user
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :encrypted_password, :uid, :provider, :is_active)
  end
  
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/plans/new.html.erb
<main class="mt-5">
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="p-5"></div>
        <h5>旅行計画案新規作成</h5>
        <%= form_with model: @plan, url:users_plans_path(@plan), local:true do |f| %>
        </br>
        <div class="form-group row">
          <label for="time" class="col-sm-2">年・月・日・時間</label>
          <div class="col-sm-10">
            <%= f.datetime_field :time %>
          </div>
        </div>
        <div class="form-group row">
          <label for="schedule" class="col-sm-2">スケジュール</label>
          <div class="col-sm-10">
            <%= f.text_area :schedule %>
          </div>
        </div>
        <div class="form-group row">
          <label for="genre" class="col-sm-2">食事(朝・昼・夜)</label>
          <div class="col-sm-10">
            <%= f.select :genre, { '朝':1, '昼':2,'夜':3 }, {include_blank: '---'} %>
          </div>
        </div>
        <div class="form-group row">
          <label for="city_name" class="col-sm-2">都市名</label>
          <div class="col-sm-10">
            <%= f.text_field :city_name, size:30 %>
          </div>
        </div>
        <div class="form-group row">
          <label for="lodgment_target_name" class="col-sm-2">宿泊先名</label>
          <div class="col-sm-10">
            <%= f.text_field :lodgment_target_name, size:30 %>
          </div>
        </div>
        <div class="form-group row">
          <label for="" class="col-sm-2">宿泊先名</label>
          <div class="col-sm-10">
          <%= f.submit "UPLOAD!" %></br>
        </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/plans/show.html.erb
<main class="mt-5">
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="p-4"></div>
        <p class="text-center">
          <center style="font-size:50px;">旅行計画案(DETAILS)</center>
        </p>
        <div class="p-3"></div>
        <form>
          <label for="name" class="col-sm-2">年・月・日・時間</label>
          　<%= @plan.time %>
          </br>
          <label for="schedule" class="col-sm-2">スケジュール</label>
          　<%= @plan.schedule %>
          </br>
          <label for="meal" class="col-sm-2">食事(朝・昼・夜)</label>
            <%= @plan.meal %>
          </br>
          <label for="city_name" class="col-sm-2">都市名</label>
            <%= @plan.city_name %>
          </br>
          <label for="lodgment_target_name" class="col-sm-2">宿泊先名</label>
            <%= @plan.lodgment_target_name %>
          </br>
        </form>
    　　    <%= link_to "editing", edit_users_plan_path, class: "btn btn-success" %>
    　　    <%= link_to "delete", users_plan_path(@plan), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %>
      </div>
    </div>
  </div>
</main>