config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users/homes#top'
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  namespace :admin do
    
    resources :posts, only: [:index, :edit, :update, :destroy]
    
    resources :plans, only: [:index, :edit, :update, :destroy]
    
    resources :users, only: [:index, :show]
    
    get '/unsubscribe' => 'admin#unsubscribe', as: 'confirm_unsubscribe'
    get '/withdraw' => 'admin#withdraw'
    patch '/withdraw' => 'admin#withdraw' 
    
  end

  namespace :users do
    
    get '/about' => 'homes#about'
    get '/my_page' => 'users#show'
    patch '/my_page' => 'users#update'
    delete '/users/sign_out' => 'sessions#destroy'
    
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    
    resources :plans, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    
    resources :users, only: [:show, :edit, :update]
    
    get '/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    get '/withdraw' => 'users#withdraw'
    patch '/withdraw' => 'users#withdraw' 
    
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  
  def cart_items_total_amount
    sum = 0
    self.cart_items.each do |cart_item|
      sum += cart_item.subtotal
    end
    return sum
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers = Customer.all
    # @customers = Customer.page(params[:page])
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_active)
  end
  
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

  def index
    @addresses = Address.all
  end
  
  def edit
    @addresses = Addresses.find(params[:id])
  end
  
  def create
    @addresses = Address.new
    @addresses.save
    redirect_to customers_addresses_path(@address.id)
  end
  
  def update
    @addresses = Addresses.find(params[:id])
    @addresses.update(addresses_params)
    redirect_to customers_address_path(@address.id)
  end
  
  def destroy
    @addresses = Addresses.find(params[:id])
    @addresses.destroy
    redirect_to customers_addresses_path
  end
  
  private
  
  def item_params
    params.require(:addresses).permit(:customer, :name, :postal_code, :address)
  end
  
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  def index
    @items = Item.all
    @names = Item.page(params[:page])
  end
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item.id)
  end
  
  def destroy
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end
  private
  
  def item_params
    params.require(:cart_items).permit(:item, :customer, :amount)
  end
  
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  
  def index
    @customers = Customer.all
    @names = Customer.page(params[:page])
  end
  
  def show
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customer_my_page_path
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number)
  end
  
end

app/controllers/customer/items_controller.rb
class  Customer::ItemsController < ApplicationController

  def index
    @items = Item.all
    @names = Item.page(params[:page])
  end
  
  def show
    @item = Item.find(params[:id])
    @items = Item.all
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price)
  end
  
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  
  def new
    @order = Order.new
  end
  
  def comfirm
  end
  
  def complete
  end

  def create
  end
  
  def index
  end
  
  def show
  end
  
  private
  
  def item_params
    params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method)
  end
  
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController

  def index
    @addresses = Address.all
    @address = Address.new
  end
  
  def create
    @addresses = Address.new(address_params)
    @addresses.save
    redirect_to customers_addresses_path
  end
  
  def edit
    @addresses = Address.find(params[:id])
  end
  
  def update
    @addresses = Address.find(params[:id])
    @addresses.update(address_params)
    redirect_to customers_address_path
  end
  
  def destroy
    @addresses = Address.find(params[:id])
    @addresses.destroy
    redirect_to customers_address_path
  end
  
  private
  
  def address_params
    params.require(:address).permit(:name, :postal_code, :address)
  end
  
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController

  def index
    @items = Item.all
    @cart_items = CartItem.all
    @names = Item.page(params[:page])
  end
  
  def create
    @item = CartItem.new(cart_item_params)
    @item.customer_id = current_customer.id
    @item.save
    redirect_to customers_cart_items_path
  end
  
  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to customers_cart_items_path
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to customers_cart_items_path
  end
  
  def destroy_all
    @cart_item = CartItem.all
    @cart_item.destroy_all
    redirect_to  customers_cart_items_path
  end
  
  private
  
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  
  def index
    @customers = Customer.all
    @names = Customer.page(params[:page])
  end
  
  def show
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_my_page_path
  end
  
  def unsubscribe
    @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_active: false)
    reset_session
    redirect_to customers_path
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number)
  end
  
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController

  def top
    @items = Item.all
    @names = Item.page(params[:page])
  end
  
  def about
  end
  
end

app/controllers/customers/items_controller.rb
class  Customers::ItemsController < ApplicationController

  def index
    @items = Item.all
    @names = Item.page(params[:page])
  end
  
  def show
    @items = Item.all
    @item = Item.find(params[:id])
    @cart = CartItem.new
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :price)
  end
  
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  
  def new
    @order = Order.new
    @addresses = Address.all
  end
  
  def confirm
    @cart_items = CartItem.all
    @order = Order.new(order_params)
    @address = Address.find(params[:order][:address_id])
    @order.postal_code = @address.postal_code
    @order.address = @address.address
    @order.name = @address.name
    @order.shipping_cost = 800
    if params[:order][:address] == "1"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address] == "2"
      @addresses = Address.find(params[:order][:address_id])
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    elsif params[:order][:address] == "3"
      address = Address.new
      address.postal_code = params[:order][:new_postal_code]
      address.address = params[:order][:new_address]
      address.name = params[:order][:new_name]
      address.customer = current_customer.id
      address.save
      @order.postal_code = address.postal_code
      @order.address = address.address
      @order.name = address.name
    end
      @order.total_payment = @order.shipping_cost + current_customer.cart_items_total_amount
      # @cart_items.each do |cart_item|
    #     @order.total_payment += cart_item.subtotal
    # end
  end
  
  def complete
  end

  def create
    @order = current_customer.orders.new(order_params)
    @order.save
    @cart_items = current_customer.cart_items.all
      @cart_items.each do |cart_item|
      @order_items = @order.order_details.new
      @order_items.item_id = cart_item.item.id
      @order_items.price = cart_item.item.price
      @order_items.amount = cart_item.amount
      @order_items.save
    end
    current_customer.cart_items.destroy_all
    redirect_to customers_orders_complete_path
  end
  
  def index
    @orders = Order.all
    @order = Order.new
  end
  
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
  
  private
  
  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method)
  end
  
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_inactive_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def reject_inactive_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && !@customer.is_active
        redirect_to new_customer_session_path
      end
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="p-5"></div>
        <h5>会員情報編集画面</h5>
        <%= form_with model: @customer, url:admin_customer_path, local:true do |f| %>
        </br>
        <form>
          <div class="form-group row">
            <label for="id" class="col-sm-2">会員ID</label>
            <div class="col-sm-10">
              <%= @customer.id %>
            </div>
          </div>
          <div class="form-group row">
            <label for="name" class="col-sm-2">氏名</label>
            <div class="col-sm-10">
              <%= f.text_field :last_name %>
              <%= f.text_field :first_name %>
            </div>
          </div>
          <div class="form-group row">
            <label for="last_name_kana" class="col-sm-2">フリガナ</label>
            <div class="col-sm-10">
              <%= f.text_field :last_name_kana %>
              <%= f.text_field :first_name_kana %>
            </div>
          </div>
          <div class="form-group row">
            <label for="postal_code" class="col-sm-2">郵便番号</label>
            <div class="col-sm-10">
              <%= f.text_field :postal_code %>
            </div>
          </div>
          <div class="form-group row">
            <label for="address" class="col-sm-2">住所</label>
            <div class="col-sm-10">
              <%= f.text_field :address %>
            </div>
          </div>
          <div class="form-group row">
            <label for="telephone_number" class="col-sm-2">電話番号</label>
            <div class="col-sm-10">
              <%= f.text_field :telephone_number %>
            </div>
          </div>
          <div class="form-group row">
            <label for="email" class="col-sm-2">メールアドレス</label>
            <div class="col-sm-10">
              <%= f.text_field :email %>
            </div>
          </div>
          <div class="form-group row">
            <label for="email" class="col-sm-3"></label>
            <%= f.submit "変更を保存", class: "btn btn-success" %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/customers/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="p-5"></div>
        <h5>会員一覧</h5>
        </br>
          <table class="table">
            <thead>
              <tr>
                <th>会員ID</th>
                <th>氏名</th>
                <th>メールアドレス</th>
                <th>ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @customers.each do |customer| %>
              <tr>
                <td><%= customer.id %></td>
                <td><%= link_to edit_admin_customer_path(customer) do %>
                    <%= customer.last_name %>
                    <%= customer.first_name %></td>
                    <% end %>
                <td><%= customer.email %></td>
                <% if customer.is_active? %>
                <td>有効</td>
                <% else %>
                <td>退会済み</td>
                <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>

app/views/admin/customers/show.html.erb
<main>
    <p id="notice"></p>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="p-5"></div>
                    <h5><%= @customer.last_name %>
                        <%= @customer.first_name %>さんの会員詳細</h5>
                    <%= form_with model: @customer, url:edit_admin_customer_path, local:true do |f| %>
                    <div class="p-1"></div>
                    <form>
                    <label for="id" class="col-sm-2 col-form-label">会員ID</label>
                        <%= @customer.id %>
                    </br>
                    <label for="name" class="col-sm-2 col-form-label">氏名</label>
                        <%= @customer.last_name %>
                        <%= @customer.first_name %>
                    </br>
                    <label for="name_kana" class="col-sm-2 col-form-label">フリガナ</label>
                        <%= @customer.last_name_kana %>
                        <%= @customer.first_name_kana %>
                    </br>
                    <label for="postal_code" class="col-sm-2 col-form-label">郵便番号</label>
                        <%= @customer.postal_code %>
                    </br>
                    <label for="address" class="col-sm-2 col-form-label">住所</label>
                        <%= @customer.address %>
                    </br>
                    <label for="telephone_number" class="col-sm-2 col-form-label">電話番号</label>
                        <%= @customer.telephone_number %>
                    </br>
                    <label for="email" class="col-sm-2 col-form-label">メールアドレス</label>
                        <%= @customer.email %>
                    </br>
                    <div class="p-3"></div>
                    <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>
                    <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</main>